// Minimal PDF generator for doctor briefing - pulls real session data
import jsPDF from 'jspdf';
import { getScans } from './storage';

export function generateDoctorPDF(patientData?: any) {
  const pdf = new jsPDF();
  const y = { current: 20 };

  // Get latest scan from session storage if no data passed
  const scans = getScans();
  const latestScan = scans[0];
  const data = patientData || {
    name: 'Patient',
    age: latestScan ? 'N/A' : 28,
    hb: latestScan?.hb || 0,
    severity: latestScan?.severity || 'Unknown',
    condition: ''
  };

  // Header
  pdf.setFontSize(16);
  pdf.text('RaktVa.Ai - Clinical Handoff', 20, y.current);
  y.current += 10;

  pdf.setFontSize(10);
  pdf.text(`Generated: ${new Date().toLocaleDateString()}`, 20, y.current);
  y.current += 15;

  // Patient info
  pdf.setFontSize(12);
  pdf.text('Patient Demographics', 20, y.current);
  y.current += 8;
  pdf.setFontSize(10);
  pdf.text(`${data.name} · ${data.age} years`, 20, y.current);
  y.current += 6;
  if (data.condition) pdf.text(data.condition, 20, y.current);
  y.current += 15;

  // CBC values
  pdf.setFontSize(12);
  pdf.text('CBC Values', 20, y.current);
  y.current += 8;
  pdf.setFontSize(10);
  pdf.text(`Hemoglobin: ${data.hb} g/dL`, 20, y.current);
  y.current += 6;
  if (data.mcv) pdf.text(`MCV: ${data.mcv} fL`, 20, y.current);
  y.current += 6;
  if (data.ferritin) pdf.text(`Ferritin: ${data.ferritin} ng/mL`, 20, y.current);
  y.current += 15;

  // Severity
  pdf.setFontSize(12);
  pdf.text('Rule-based Severity', 20, y.current);
  y.current += 8;
  pdf.setFontSize(10);
  pdf.text(data.severity || 'Unknown', 20, y.current);
  y.current += 15;

  // Actions
  pdf.setFontSize(12);
  pdf.text('Doctor Action Checklist', 20, y.current);
  y.current += 8;
  pdf.setFontSize(10);
  pdf.text('☑ Escalate for same-day clinical review', 20, y.current);
  y.current += 6;
  pdf.text('☑ Confirm iron therapy adherence', 20, y.current);
  y.current += 6;
  pdf.text('☑ Schedule re-screen in 30 days', 20, y.current);

  // Footer
  pdf.setFontSize(8);
  pdf.text('Generated by RaktVa.Ai | Anemia Mukt Bharat', 20, 280);

  pdf.save(`raktva-briefing-${new Date().toISOString().split('T')[0]}.pdf`);
}
