// Minimal PDF generator for doctor briefing
import jsPDF from 'jspdf';

export function generateDoctorPDF(patientData: any) {
  const pdf = new jsPDF();
  const y = { current: 20 };

  // Header
  pdf.setFontSize(16);
  pdf.text('RaktVa.Ai - Clinical Handoff', 20, y.current);
  y.current += 10;

  pdf.setFontSize(10);
  pdf.text(`Generated: ${new Date().toLocaleDateString()}`, 20, y.current);
  y.current += 15;

  // Patient info
  pdf.setFontSize(12);
  pdf.text('Patient Demographics', 20, y.current);
  y.current += 8;
  pdf.setFontSize(10);
  pdf.text(`${patientData.name} · ${patientData.age} years`, 20, y.current);
  y.current += 6;
  pdf.text(patientData.condition || '', 20, y.current);
  y.current += 15;

  // CBC values
  pdf.setFontSize(12);
  pdf.text('CBC Values', 20, y.current);
  y.current += 8;
  pdf.setFontSize(10);
  pdf.text(`Hemoglobin: ${patientData.hb} g/dL`, 20, y.current);
  y.current += 6;
  if (patientData.mcv) pdf.text(`MCV: ${patientData.mcv} fL`, 20, y.current);
  y.current += 6;
  if (patientData.ferritin) pdf.text(`Ferritin: ${patientData.ferritin} ng/mL`, 20, y.current);
  y.current += 15;

  // Severity
  pdf.setFontSize(12);
  pdf.text('Rule-based Severity', 20, y.current);
  y.current += 8;
  pdf.setFontSize(10);
  pdf.text(patientData.severity || 'SEVERE ANEMIA', 20, y.current);
  y.current += 15;

  // Actions
  pdf.setFontSize(12);
  pdf.text('Doctor Action Checklist', 20, y.current);
  y.current += 8;
  pdf.setFontSize(10);
  pdf.text('☑ Escalate for same-day clinical review', 20, y.current);
  y.current += 6;
  pdf.text('☑ Confirm iron therapy adherence', 20, y.current);
  y.current += 6;
  pdf.text('☑ Schedule re-screen in 30 days', 20, y.current);

  // Footer
  pdf.setFontSize(8);
  pdf.text('Generated by RaktVa.Ai | Anemia Mukt Bharat', 20, 280);

  pdf.save('doctor-briefing.pdf');
}
